version: "3"

vars:
  IMAGE_REPO: madhan13/devops-directive-kubernetes-course-load-generator-python
  IMAGE_TAG:
    sh: git describe --tags --always --first-parent --match "[0-9]*.[0-9]*.[0-9]*"

tasks:
  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} .

  build-container-image-multi-arch:
    desc: Build container image for multiple architectures
    cmds:
      - docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .

  push-container-image:
    desc: Push container image
    cmds:
      - docker push {{.IMAGE_REPO}}:{{.IMAGE_TAG}}

  install:
    desc: Install load generator dependencies
    cmds:
      - poetry install --no-root

  run:
    desc: Start load generator
    cmds:
      # api-golang is listening on port 8000
      - API_URL=http://localhost:8000/ DELAY_MS=100 poetry run python main.py
